spring:
  application:
    name: Ecommerce App
  datasource:
    hikari:
      auto-commit: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce
    username: root
    password: root
  data:
    rest:
      base-path: /api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      platform: mysql
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      mode: always

